default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: blog_final_development

test:
  <<: *default
  database: blog_final_test

production:
  <<: *default
  database: blog_final_production
 